[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
    https://github.com/PaulStoffregen/OneWire.git#386a8d0715781fd38a61c7f0a753c2f988a2abca
    https://github.com/milesburton/Arduino-Temperature-Control-Library.git#e3c727618653484bc7365ef238f46983fddc66b4
