[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
    https://github.com/vincasmiliunas/ESP8266-Arduino-SHT21.git#cbef21004dbf9963bd2a4fd4ca605dc52572abac
    https://github.com/adafruit/Adafruit_Sensor.git#967e6fab4a37e6298fbf56a8b97de5a369fc0735
    https://github.com/adafruit/Adafruit_BMP280_Library.git#95853706eac7185967bc9917c692c70b54798db2
    https://github.com/adafruit/Adafruit_BusIO.git#186bfb005c6d4b597a09290cb3e451c30a5baa97
    https://github.com/squix78/esp8266-oled-ssd1306.git#4.0.0
