[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
    https://github.com/adafruit/Adafruit_Sensor.git#967e6fab4a37e6298fbf56a8b97de5a369fc0735
    https://github.com/adafruit/Adafruit_TSL2561.git#0856f62c1d1087663e361441cb530c3cf7a47f39
