[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
    https://github.com/arcao/Syslog.git#e9c2eea7a91fdda3a55f9df2ebc122f3152da02d
    https://github.com/256dpi/arduino-mqtt.git#7afcfb15870252b5307ec997c2eeeb42d4292bab
    https://github.com/JChristensen/Timer.git#v2.1
