[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
    https://github.com/adafruit/Adafruit_Sensor.git#967e6fab4a37e6298fbf56a8b97de5a369fc0735
    https://github.com/adafruit/Adafruit_BME280_Library.git#427d80dbdf20af00c67ec49425a0ecdd79d7f239
    https://github.com/adafruit/Adafruit_BusIO.git#186bfb005c6d4b597a09290cb3e451c30a5baa97
